[package]
name = "assumevalid"
version = "0.1.0"
edition = "2024_07"

[executable]

[dependencies]
cairo_execute = "2.11.4"
consensus = { path = "../consensus" }

[dev-dependencies]
cairo_test.workspace = true

[scripts]
build-agg = "cairo-compile src/aggregator.cairo --proof_mode --output ../../target/proving/aggregator.json"
